spring:
  datasource:
    driverClassName: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL:jdbc:mysql://localhost:3306/email_marketing}
    username: ${DB_USERNAME:emtest}
    password: ${DB_PASSWORD:emtest}
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
com:
  example:
    demo:
      jwt:
        expired_token: ${EXPIRED_TOKEN:86400}
        expired_refresh_token: ${EXPIRED_REFRESH_TOKEN:604800}
        issuer: ${ISSUER:http://localhost:8000}
        secret: ${SECRET:secret4684646684646846468488468suhfusdhfiseifhisifhisheifhsiehfihsihe}
server:
  servlet:
    context-path: /email-service/v1
cron:
  reschedule: ${RESCHEDULE_TASK_CRON_EXPRESSION:* 0/10 * * * *}
thread.pool:
  size: ${THREAD_POOL_SIZE:5}
