spring:
  datasource:
    driverClassName: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL:jdbc:mysql://localhost:3306/email_marketing}
    username: ${DB_USERNAME:emtest}
    password: ${DB_PASSWORD:emtest}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
com:
  example:
    demo:
      jwt:
        expired_token: ${EXPIRED_TOKEN:86400}
        expired_refresh_token: ${EXPIRED_REFRESH_TOKEN:604800}
        issuer: ${ISSUER:http://localhost:8000}
        secret: ${SECRET:secret4684646684646846468488468suhfusdhfiseifhisifhisheifhsiehfihsihe}
server:
  servlet:
    context-path: /email-service/v1
thread.pool:
  size: ${THREAD_POOL_SIZE:5}
cron:
  reschedule: ${CRON_RESCHEDULE:0/10 * * * * }
file:
  controller:
    endpoint: ${FILE_CONTROLLER_ENDPOINT:http://localhost:8080/email-service/v1}
