spring:
  datasource:
    driverClassName: ${DB_DRIVER_CLASS_NAME:com.mysql.jdbc.Driver}
    url: ${DB_URL:jdbc:mysql://localhost:3306/email_marketing}
    username: ${DB_USERNAME:emtest}
    password: ${DB_PASSWORD:emtest}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
com:
  example:
    demo:
        jwt:
            expired_token: ${EXPIRED_TOKEN:2700}
            expired_refresh_token: ${EXPIRED_REFRESH_TOKEN:86400}
            issuer: ${ISSUER:http://localhost:8000}
            secret: ${SECRET:secret4684646684646846468488468suhfusdhfiseifhisifhisheifhsiehfihsihe}
server:
  servlet:
    context-path: /email-service/v1